server:
  port: 8002
spring:
  application:
    name: flight-search
    version: 1.0
    title: flight-search
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        jdbc:
          batch_size: 100
        order_updates: true
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/zephyx
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
amadeus:
  api:
    key: sIj65GRyjsjIb5rZS93r8osZunt3GZ8L
    secret: e1psrgVibhVJvGqE
    access:
      token: kB3CzKuAgzKlRZbD7wy8tMHmxrKQ
